"""m3: Feat, agregar updated_at en prospecto

Revision ID: 0122a2ce8ea1
Revises: 07f706ae928e
Create Date: 2026-06-22 15:41:24.800467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0122a2ce8ea1'
down_revision: Union[str, Sequence[str], None] = '07f706ae928e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospecto', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospecto', 'updated_at')
    # ### end Alembic commands ###
