"""init juanferDb v1

Revision ID: 1862ff089733
Revises: 
Create Date: 2026-04-24 09:18:10.596966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1862ff089733'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # --- Trigger manual: Función para updated_at ---
    op.execute("""
        CREATE OR REPLACE FUNCTION fn_set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = CURRENT_TIMESTAMP;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aseguradora',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('banco',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('requisitos', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('categoria_mensaje',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estado_cambio_intermediario',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estado_cotizacion',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estado_poliza',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), server_default=sa.text("'gris'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estado_prospecto',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estado_tramite_banco',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('link_proceso',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nivel_alerta',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('permiso',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('ramo',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('rol',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipo_documento',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('config_alerta',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('umbral_dias', sa.Integer(), nullable=False),
    sa.Column('nivel_id', sa.BigInteger(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['nivel_id'], ['nivel_alerta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantilla_mensaje',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('categoria_id', sa.BigInteger(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_mensaje.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol_permiso',
    sa.Column('rol_id', sa.BigInteger(), nullable=False),
    sa.Column('permiso_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol_id', sa.BigInteger(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.String(length=50), nullable=False),
    sa.Column('campo', sa.String(length=50), nullable=True),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_nuevo', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tipo_documento_id', sa.BigInteger(), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('responsable_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipo_documento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_documento')
    )
    op.create_index('idx_cliente_documento', 'cliente', ['numero_documento'], unique=False)
    op.create_table('historial_responsable_cliente',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_anterior_id', sa.BigInteger(), nullable=True),
    sa.Column('usuario_nuevo_id', sa.BigInteger(), nullable=False),
    sa.Column('realizado_por_id', sa.BigInteger(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('polizas_afectadas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['realizado_por_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_anterior_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_nuevo_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_historial_resp_cliente', 'historial_responsable_cliente', ['cliente_id', sa.text('fecha DESC')], unique=False)
    op.create_table('prospecto',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('producto_id', sa.BigInteger(), nullable=False),
    sa.Column('estado_id', sa.BigInteger(), nullable=False),
    sa.Column('responsable_id', sa.BigInteger(), nullable=True),
    sa.Column('fecha_contacto', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estado_id'], ['estado_prospecto.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotizacion',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('prospecto_id', sa.BigInteger(), nullable=True),
    sa.Column('aseguradora_id', sa.BigInteger(), nullable=True),
    sa.Column('producto_id', sa.BigInteger(), nullable=True),
    sa.Column('estado_id', sa.BigInteger(), nullable=False),
    sa.Column('responsable_id', sa.BigInteger(), nullable=True),
    sa.Column('fecha_cotizacion', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aseguradora_id'], ['aseguradora.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estado_id'], ['estado_cotizacion.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prospecto_id'], ['prospecto.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cotizacion_estado_responsable', 'cotizacion', ['estado_id', 'responsable_id'], unique=False)
    op.create_table('nota_prospecto',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prospecto_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['prospecto_id'], ['prospecto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poliza',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('asegurado_nombre', sa.String(length=150), nullable=True),
    sa.Column('ramo_id', sa.BigInteger(), nullable=False),
    sa.Column('aseguradora_id', sa.BigInteger(), nullable=False),
    sa.Column('producto_id', sa.BigInteger(), nullable=False),
    sa.Column('estado_id', sa.BigInteger(), nullable=False),
    sa.Column('responsable_id', sa.BigInteger(), nullable=True),
    sa.Column('cotizacion_id', sa.BigInteger(), nullable=True),
    sa.Column('fecha_solicitud', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('fecha_expedicion', sa.Date(), nullable=True),
    sa.Column('numero_poliza', sa.String(length=50), nullable=True),
    sa.Column('prima', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fecha_expedicion >= fecha_solicitud', name='check_fecha_expedicion_valida'),
    sa.CheckConstraint('prima > 0', name='check_prima_positiva'),
    sa.ForeignKeyConstraint(['aseguradora_id'], ['aseguradora.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizacion.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['estado_id'], ['estado_poliza.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ramo_id'], ['ramo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cotizacion_id'),
    sa.UniqueConstraint('numero_poliza')
    )
    op.create_index('idx_poliza_created_at', 'poliza', ['created_at'], unique=False)
    op.create_index('idx_poliza_estado', 'poliza', ['estado_id'], unique=False)
    op.create_index('idx_poliza_fecha_solicitud', 'poliza', ['fecha_solicitud'], unique=False)
    op.create_index('idx_poliza_fechas', 'poliza', ['fecha_solicitud', 'fecha_expedicion'], unique=False, postgresql_where=sa.text('fecha_expedicion IS NULL'))
    op.create_index('idx_poliza_responsable', 'poliza', ['responsable_id'], unique=False)
    op.create_table('cambio_intermediario',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('poliza_id', sa.BigInteger(), nullable=False),
    sa.Column('estado_id', sa.BigInteger(), nullable=False),
    sa.Column('fecha_cambio', sa.Date(), nullable=True),
    sa.Column('fecha_limite_reclamacion', sa.Date(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['estado_id'], ['estado_cambio_intermediario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['poliza_id'], ['poliza.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cancelacion',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('poliza_id', sa.BigInteger(), nullable=False),
    sa.Column('responsable_id', sa.BigInteger(), nullable=False),
    sa.Column('fecha_cancelacion', sa.Date(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('valor_negativo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('es_definitiva', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valor_negativo <= 0', name='check_valor_negativo'),
    sa.ForeignKeyConstraint(['poliza_id'], ['poliza.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poliza_id')
    )
    op.create_table('endoso_banco',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('poliza_id', sa.BigInteger(), nullable=False),
    sa.Column('banco_id', sa.BigInteger(), nullable=False),
    sa.Column('responsable_id', sa.BigInteger(), nullable=False),
    sa.Column('tomador_id', sa.BigInteger(), nullable=False),
    sa.Column('estado_tramite_id', sa.BigInteger(), nullable=False),
    sa.Column('contacto_alternativo', sa.String(length=20), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['banco_id'], ['banco.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['estado_tramite_id'], ['estado_tramite_banco.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['poliza_id'], ['poliza.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tomador_id'], ['cliente.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_responsable',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('poliza_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_anterior_id', sa.BigInteger(), nullable=True),
    sa.Column('usuario_nuevo_id', sa.BigInteger(), nullable=False),
    sa.Column('realizado_por_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo', sa.String(length=20), server_default='TRASPASO', nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo IN ('TRASPASO', 'REASIGNACION')", name='check_tipo_movimiento'),
    sa.ForeignKeyConstraint(['poliza_id'], ['poliza.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['realizado_por_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_anterior_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_nuevo_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_historial_responsable_nuevo', 'historial_responsable', ['usuario_nuevo_id', sa.text('fecha DESC')], unique=False)
    op.create_index('idx_historial_responsable_poliza', 'historial_responsable', ['poliza_id', sa.text('fecha DESC')], unique=False)
    op.execute("CREATE TRIGGER trg_cliente_updated_at BEFORE UPDATE ON cliente FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();")
    op.execute("CREATE TRIGGER trg_poliza_updated_at BEFORE UPDATE ON poliza FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_poliza_updated_at ON poliza;")
    op.execute("DROP TRIGGER IF EXISTS trg_cliente_updated_at ON cliente;")
    op.execute("DROP FUNCTION IF EXISTS fn_set_updated_at();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_historial_responsable_poliza', table_name='historial_responsable')
    op.drop_index('idx_historial_responsable_nuevo', table_name='historial_responsable')
    op.drop_table('historial_responsable')
    op.drop_table('endoso_banco')
    op.drop_table('cancelacion')
    op.drop_table('cambio_intermediario')
    op.drop_index('idx_poliza_responsable', table_name='poliza')
    op.drop_index('idx_poliza_fechas', table_name='poliza', postgresql_where=sa.text('fecha_expedicion IS NULL'))
    op.drop_index('idx_poliza_fecha_solicitud', table_name='poliza')
    op.drop_index('idx_poliza_estado', table_name='poliza')
    op.drop_index('idx_poliza_created_at', table_name='poliza')
    op.drop_table('poliza')
    op.drop_table('nota_prospecto')
    op.drop_index('idx_cotizacion_estado_responsable', table_name='cotizacion')
    op.drop_table('cotizacion')
    op.drop_table('prospecto')
    op.drop_index('idx_historial_resp_cliente', table_name='historial_responsable_cliente')
    op.drop_table('historial_responsable_cliente')
    op.drop_index('idx_cliente_documento', table_name='cliente')
    op.drop_table('cliente')
    op.drop_table('auditoria')
    op.drop_table('usuario')
    op.drop_table('rol_permiso')
    op.drop_table('plantilla_mensaje')
    op.drop_table('config_alerta')
    op.drop_table('tipo_documento')
    op.drop_table('rol')
    op.drop_table('ramo')
    op.drop_table('producto')
    op.drop_table('permiso')
    op.drop_table('nivel_alerta')
    op.drop_table('link_proceso')
    op.drop_table('estado_tramite_banco')
    op.drop_table('estado_prospecto')
    op.drop_table('estado_poliza')
    op.drop_table('estado_cotizacion')
    op.drop_table('estado_cambio_intermediario')
    op.drop_table('categoria_mensaje')
    op.drop_table('banco')
    op.drop_table('aseguradora')
    # ### end Alembic commands ###
