"""m3_prospectos_pipeline

Revision ID: 871cc6d526bd
Revises: 1862ff089733
Create Date: 2026-06-19 18:58:56.454298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871cc6d526bd'
down_revision: Union[str, Sequence[str], None] = '1862ff089733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarea',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prospecto_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_programada', sa.Date(), nullable=True),
    sa.Column('completada', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('completada_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prospecto_id'], ['prospecto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversacion',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prospecto_id', sa.BigInteger(), nullable=True),
    sa.Column('cliente_id', sa.BigInteger(), nullable=True),
    sa.Column('canal', sa.String(length=20), server_default='whatsapp', nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='abierta', nullable=False),
    sa.Column('waba_conversation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("canal IN ('whatsapp', 'email', 'telefono', 'presencial')", name='ck_conversacion_canal'),
    sa.CheckConstraint("estado IN ('abierta', 'cerrada', 'esperando')", name='ck_conversacion_estado'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prospecto_id'], ['prospecto.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensaje',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversacion_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=True),
    sa.Column('direccion', sa.String(length=10), nullable=False),
    sa.Column('tipo_canal', sa.String(length=30), server_default='texto', nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('waba_message_id', sa.String(length=100), nullable=True),
    sa.Column('estado_entrega', sa.String(length=20), server_default='pendiente', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direccion IN ('inbound', 'outbound')", name='ck_direccion_mensaje'),
    sa.CheckConstraint("estado_entrega IN ('pendiente', 'enviado', 'entregado', 'leido', 'fallido')", name='ck_estado_entrega_mensaje'),
    sa.CheckConstraint("tipo_canal IN ('texto', 'imagen', 'documento', 'audio', 'whatsapp_template', 'whatsapp_libre')", name='ck_tipo_canal_mensaje'),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversacion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cliente', sa.Column('correo', sa.String(length=100), nullable=True))
    op.add_column('cliente', sa.Column('ocupacion', sa.String(length=100), nullable=True))
    op.add_column('cliente', sa.Column('ciudad', sa.String(length=80), nullable=True))
    op.add_column('estado_prospecto', sa.Column('color', sa.String(length=30), nullable=False))
    op.add_column('estado_prospecto', sa.Column('orden', sa.SmallInteger(), nullable=False))
    op.add_column('estado_prospecto', sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('estado_prospecto', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('prospecto', sa.Column('canal_origen', sa.String(length=20), server_default='manual', nullable=False))
    op.add_column('prospecto', sa.Column('aseguradora_interes_id', sa.BigInteger(), nullable=True))
    op.add_column('prospecto', sa.Column('ramo_interes_id', sa.BigInteger(), nullable=True))
    op.add_column('prospecto', sa.Column('poliza_id', sa.BigInteger(), nullable=True))
    op.add_column('prospecto', sa.Column('fecha_primer_contacto', sa.Date(), nullable=True))
    op.add_column('prospecto', sa.Column('fecha_ultimo_contacto', sa.Date(), nullable=True))
    op.add_column('prospecto', sa.Column('proximo_contacto', sa.Date(), nullable=True))
    op.add_column('prospecto', sa.Column('intentos_contacto', sa.SmallInteger(), server_default=sa.text('0'), nullable=False))
    op.add_column('prospecto', sa.Column('observaciones', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'prospecto', 'ramo', ['ramo_interes_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'prospecto', 'poliza', ['poliza_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'prospecto', 'aseguradora', ['aseguradora_interes_id'], ['id'], ondelete='SET NULL')
    op.drop_column('prospecto', 'fecha_contacto')

    op.create_check_constraint(
        'ck_canal_origen', 'prospecto',
        "canal_origen IN ('manual', 'whatsapp', 'formulario', 'csv')"
    )
    op.create_check_constraint(
        'ck_intentos_contacto', 'prospecto',
        "intentos_contacto >= 0 AND intentos_contacto <= 7"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospecto', sa.Column('fecha_contacto', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'prospecto', type_='foreignkey')
    op.drop_constraint(None, 'prospecto', type_='foreignkey')
    op.drop_constraint(None, 'prospecto', type_='foreignkey')
    op.drop_column('prospecto', 'observaciones')
    op.drop_column('prospecto', 'intentos_contacto')
    op.drop_column('prospecto', 'proximo_contacto')
    op.drop_column('prospecto', 'fecha_ultimo_contacto')
    op.drop_column('prospecto', 'fecha_primer_contacto')
    op.drop_column('prospecto', 'poliza_id')
    op.drop_column('prospecto', 'ramo_interes_id')
    op.drop_column('prospecto', 'aseguradora_interes_id')
    op.drop_column('prospecto', 'canal_origen')
    op.drop_column('estado_prospecto', 'created_at')
    op.drop_column('estado_prospecto', 'activo')
    op.drop_column('estado_prospecto', 'orden')
    op.drop_column('estado_prospecto', 'color')
    op.drop_column('cliente', 'ciudad')
    op.drop_column('cliente', 'ocupacion')
    op.drop_column('cliente', 'correo')
    op.drop_table('mensaje')
    op.drop_table('conversacion')
    op.drop_table('tarea')
    # ### end Alembic commands ###
